In [5]:
#NumPy ia a python Library
#Numpy is used for working with arrays.
#NUmpy is short for NUMERICAL PYTHON

import numpy as np
a=np.array([1,2,3,45,6])
print(a)
print(type(a))

[ 1  2  3 45  6]
<class 'numpy.ndarray'>


In [5]:
# WHAT IS NUMPY '''
'''numpy is a python library used for working with arrays.
It also has function for working in domain of lineaar algebra, fourier transformatiom and matrices.
numpy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
'''
# WHY USE NUMPY 
'''In python we have lists that serve the purpose of array , but they are slow to process .
Numpy aims to provide an array object that is upto 50x faster than traditionalpython lists.
the array object in Numpy is called ndarray.
It provides a lot of supporting functions that make working with ndarray is veray easy.
Arrays are very frequently used in data science,where speed and resources are very important.'''

# why is NUMOY faster than lists?
'''Numpy array are stored at one continues place in memory unlike lists, so processes can access and manipulate them very efficiently.
The behavior is called locality of reference in computer science.
This is the main reason why Numpyis faster than lists . Also it is optimized towork with latest CPU architectures. '''

# which language is Numpy written in?
''' numpy is a pyhton and is written partially in python , but most of the parts that require fast computationa are written in C or C++.'''



' numpy is a pyhton and is written partially in python , but most of the parts that require fast computationa are written in C or C++.'

In [7]:
# Installation of Numpy
'''if you have python PIP is already installled on a system, then installaton of Numpy is very easy'''
''' > pip install numpy
    >import numpy      '''


' > pip install numpy\n    >import numpy      '

In [19]:
import numpy
arr=numpy.array([1,2,3,4,5,5,4,3])
print(arr)

# we can use alias it is very simply
import numpy as nu
a=nu.array([10,1,2,1,1,1,1])
print(a)

# checking the Numpy Version
# ------> __version__ this is the keyword
nu.__version__

[1 2 3 4 5 5 4 3]
[10  1  2  1  1  1  1]


'1.26.4'

In [29]:
'''Create Numpy ndarray object'''
# to create an nd arrray ,, we can pass a list , tuple or array-like object into the array()
#methid , and it will be converted into an ndarry:

import numpy as np
arr=np.array((1,2,3,4,5))
arr1=np.array([1,2,3,4,5,6,7])
print(arr)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5 6 7]


In [115]:
# DIMENSIONS IN ARRAYS
'''
0-D Arrays or scalar
1-d Arrays  or uni-dimensional array
2-D Array
3-D Arrays
'''

# 0-D arr
arr=np.array(200)
print(arr)

#1-D arr
arr1=np.array([100,200,300,400,500])
print(arr1)

#2-D arr
arr2=np.array([[100,200,300,400,500],[1,2,3,4,5]])
print(arr2)

#3-D arr
arr3=np.array([[[100,200,300,400,500],[1,2,3,4,5]],[[110,230,309,445,592],[1,2,3,4,5]]])
print(arr3)
type(arr3)

# check the which dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


# Higher Dimensional Arrays
#we can create n no.of dimnesions
arr=np.array([1,2,3,4,5,6,7,8],ndmin=10)
print(arr)
print('no.of dimensions:',arr.ndim)

200
[100 200 300 400 500]
[[100 200 300 400 500]
 [  1   2   3   4   5]]
[[[100 200 300 400 500]
  [  1   2   3   4   5]]

 [[110 230 309 445 592]
  [  1   2   3   4   5]]]
0
1
2
3
[[[[[[[[[[1 2 3 4 5 6 7 8]]]]]]]]]]
no.of dimensions: 10


In [117]:
# ARRAy indexing
arr=[1,2,3,1.2,'q','w',5,6,7,8,9,10,True,False,0,1]
print(arr)
print(arr[0])
print(arr[6:])
print(arr[-8:-1])
print(arr[6:-4])
print(arr[:2])

[1, 2, 3, 1.2, 'q', 'w', 5, 6, 7, 8, 9, 10, True, False, 0, 1]
1
[5, 6, 7, 8, 9, 10, True, False, 0, 1]
[7, 8, 9, 10, True, False, 0]
[5, 6, 7, 8, 9, 10]
[1, 2]


In [151]:
arr2=np.array([[100,200,300,400,500],[1,2,3,4,5]])
print(arr2)
print(arr2[0,4])
print(arr2[1,3])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,0,2])
print(arr[1,1,-2])
print(arr[1,-1])
print(arr2[0,-3])

[[100 200 300 400 500]
 [  1   2   3   4   5]]
500
4
3
11
[10 11 12]
300


In [205]:
''' NumPy Array Slicing '''
# it means taking  elemments froom one index to another given index 
# [start : end ],[start:end:step]
#if we don't pass start its considered 0
# if we don't pass end its considered length of the aarray in that dimension
# if we don't pass step its considered 1

arr1=np.array([100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500])
print(arr1[-6:-1])
print(arr1[1:5])
print(arr1[0:11:2])
print(arr1[1:10:3])
print(arr1[::2])
print()
arr2=np.array([[100,200,300,400,500],[1,2,3,4,5]])
print(arr2[1,1:4])
print(arr2[1,1:4])
print(arr2[0:2,2]) # it is very difficult so much connfusion
print(arr2[0:2,1:3])

[1000 1100 1200 1300 1400]
[200 300 400 500]
[ 100  300  500  700  900 1100]
[200 500 800]
[ 100  300  500  700  900 1100 1300 1500]

[2 3 4]
[2 3 4]
[300   3]
[[200 300]
 [  2   3]]


In [9]:
# Data types
import numpy as np
arr= np.array([1,23,4,5,6,7])
print(arr)
print(arr.dtype)

[ 1 23  4  5  6  7]
int32


In [13]:
arr=np.array(['ravi','kumar','manu','mani'])
print(arr.dtype)

<U5


In [23]:
# Creating Arrays with a defined dats type

arr= np.array([1,23,4,5,6,7],dtype='S')
print(arr.dtype)

|S2


In [45]:
arr= np.array([1,23,4,5,6,7],dtype='U')
print(arr.dtype)

<U2


In [13]:
# If a type is given elements can't be casted then Numpy will raise a valueError
arr= np.array([1,23,'a',5,6.3,7],dtype=int)
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

In [71]:
#Converting Dat type on Existing arrays
''' in this concept we are using type casting concept
>we useful to method astype() 
>like float into integer '''

# arr=np.array([1.1,2.2,3.3,4.4,5.5])
# print(arr.astype('i'))
# print(arr.dtype)
#      (0r)
arr=np.array([1.1,2.2,3.3,4.4,5.5])
print(arr.astype(int))
print(arr.dtype)

[1 2 3 4 5]
float64


In [79]:
arr=np.array([1,2,3,4,5,0,9,2,-1,0.0,-0.0])
print(arr.astype(bool))
print(arr.dtype)


[ True  True  True  True  True False  True  True  True False False]
float64


In [111]:
# diffference between the copy and view
''' first of all copy is nothing but it is one data , this data copy that means no 
channges of the data and also not affect   the original arrray
>another one is view is does not own the data ,also channges the data and affect the original array '''

arr=np.array([1,2,32.3,'de',3,'d'])
# arr[0]=42
# print(arr)
# print(arr.copy())
x=arr.copy()
arr[0]=35
print(arr)
print(x)

print()

arr=np.array([1,2,32.3,'de',3,'d'])
y=arr.view()
arr[4]=35
print(arr)
print(y)

# if check the array is owns the data or not
print()
x=arr.copy()
y=arr.view()
print(x.base)   # it doesn't own the data
print(y.base)   # it owns the data

['35' '2' '32.3' 'de' '3' 'd']
['1' '2' '32.3' 'de' '3' 'd']

['1' '2' '32.3' 'de' '35' 'd']
['1' '2' '32.3' 'de' '35' 'd']

None
['1' '2' '32.3' 'de' '35' 'd']


In [19]:
'''shape of the Array '''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [5]:
import numpy as np
arr=np.array([])
arr=np.array([1,2,3,4,5,6], ndmin=5)
print(arr)
print(arr.shape)
print()
arr=np.array([[[[[[1, 2 ,3, 4, 5, 6]]]]],[[[[[1, 2, 3, 4 ,5 ,6]]]]]])    #'''can't understandable'''
print(arr.shape)


[[[[[1 2 3 4 5 6]]]]]
(1, 1, 1, 1, 6)

(2, 1, 1, 1, 1, 6)


In [5]:
#'''Reshaping arrays '''
''' reshaping means changing the shape of the array
  > the shape of the array is the number of elements in each dimension.
  >By rshaping ea can add or remove dimensions or change number of elements in each dimension'''

# reshape with 1-D to 2-D
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [41]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
newarr=arr.reshape(4,3)
print(newarr)
print()
newarr=arr.reshape(2,6)
print(newarr)
print()
newarr=arr.reshape(3,4)
print(newarr)
print()
newarr=arr.reshape(1,12)
print(newarr)
print()
newarr=arr.reshape(12,1)
print(newarr)
print()
newarr=arr.reshape(2,3,2)
print(newarr)
print()
newarr=arr.reshape(3,2,2)
print(newarr)

print()
newarr=arr.reshape(2,2,3)
print(newarr)



(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
newarr=arr.reshape(1,6,2)
print(newarr)
print()
newarr=arr.reshape(6,2,1)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]


In [67]:
# UNKNOWN DIMENSION
''' YOu are allowwed to have ''unknown'' dimesion.
 >Meaning that you do not have to specify an number for one of he dimensions in the reshape method
 > pass the -1 value and Numpy will calculate this number for you
 '''
newarr=arr.reshape(2,2,-1)
print(newarr)
print()

# Flattering arrays
'''flattering array means converting a multidimensional array into !-D array
  > we can use reshape(-1) to do this. '''

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.reshape(-1))

#      (or)
print(arr.reshape(8))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [79]:
# Iterating Arrays
'''
Iterating means iterate each element in one by one. '''
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i)

1
2
3
4
5
6


In [81]:
# 2-D iterating
arr=np.array([[1,2,3,4,5,6],[8,9,10,11,12,13]])
for i in arr:
    print(i)

[1 2 3 4 5 6]
[ 8  9 10 11 12 13]


In [91]:
# 3-D Iterating
'''If we iterate on a n-D array it will go through n-1th dimension one by one.'''
arr=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 8  9 10]
 [11 12 13]]


In [87]:
arr=np.array([[1,2,3,4,5,6],[8,9,10,11,12,13]])
for x in arr:
    for y in x: 
        print(y)



1
2
3
4
5
6
8
9
10
11
12
13


In [95]:
arr=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
8
9
10
11
12
13


In [11]:
# iterating Arrays using nditer()
'''Thefunction nditer() is a helping function that can be used from very basic to very advanced iteratioon. It solves bsic wwhich we face initeration, lets go through it with examples.'''
# in basic for loops,iterating through each scalar of an arrya of an array we need to ude n for loops which can be difficult to write for with very high dimensionality
arr=np.array([1,2,3,4])
for k in np.nditer(arr):
    print(k)


1
2
3
4


In [47]:
# iterating Array with different data Types :
''' we can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
NumPy doesn't change the data type  of the element in-place (where the elemets is in array) so it needs some other space to perform this acton,
that extra space is called buffer , and in order to enable it in nditer() and pass flags=['buffered']. '''
arr=np.array([1,2,3,4])
for k in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(k)
# iteratign with Difeerent step size   or  slicing

arr=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
for x in np.nditer(arr[:,::3]) :
    print(x)


b'1'
b'2'
b'3'
b'4'
1
4
7
10
1
4
7
10


In [53]:
# ENumerated Iterationn using ndenumerate()
''' Enumeration means mentioning sequence number of something one by one.
 sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases. '''
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i, x in  np.ndenumerate(arr):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10


In [59]:
#2-D Enumerated
arr=np.array([[1,2,3,4,5,6,7,8,9.10],[1,2,3,4,5,6,7,8,9.10],[1,2,3,4,5,6,7,8,9.10]])
for idx, x in  np.ndenumerate(arr):
    print(idx,x)
    

(0, 0) 1.0
(0, 1) 2.0
(0, 2) 3.0
(0, 3) 4.0
(0, 4) 5.0
(0, 5) 6.0
(0, 6) 7.0
(0, 7) 8.0
(0, 8) 9.1
(1, 0) 1.0
(1, 1) 2.0
(1, 2) 3.0
(1, 3) 4.0
(1, 4) 5.0
(1, 5) 6.0
(1, 6) 7.0
(1, 7) 8.0
(1, 8) 9.1
(2, 0) 1.0
(2, 1) 2.0
(2, 2) 3.0
(2, 3) 4.0
(2, 4) 5.0
(2, 5) 6.0
(2, 6) 7.0
(2, 7) 8.0
(2, 8) 9.1


In [155]:
# JOining Arrays 
# 1-D ARRAy joining
arr1=np.array([1,2,3,4,5,6,7,8,9.5,10])
arr2=np.array([11,12,13,14,15,16,17,18,19.6,20])
arr=np.concatenate((arr1,arr2))
print(arr)


# 2_ D ARRAY Joining
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.5 10.  11.  12.  13.  14.
 15.  16.  17.  18.  19.6 20. ]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [161]:
# JOining Arrays using Stack Functions
''' stacking is same as concatenate, the only difference is that stacking is done along a new axias.'''
arr1=np.array([1,2,3,4,5,6,7,8,95,10])
arr2=np.array([11,12,13,14,15,16,17,18,196,20])
arr=np.stack((arr1,arr2),axis=1)
print(arr)
print()
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
arr=np.stack((arr1,arr2))
print(arr)

[[  1  11]
 [  2  12]
 [  3  13]
 [  4  14]
 [  5  15]
 [  6  16]
 [  7  17]
 [  8  18]
 [ 95 196]
 [ 10  20]]

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [173]:
# stacking along Rows
''' Numpy provides a helper function : hstack() to stack rows. '''
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
arr=np.hstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [175]:
# Stacking Along columns
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
arr=np.vstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [177]:
# stacking along height (depth)
''' numpy provides a helper function: dstack() to stack along height, which is ths same as depth. '''
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
arr=np.dstack((arr1,arr2))
print(arr)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


In [3]:
# NumPy Splitting Array
# 1-d  to two 1-d
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [229]:
#2-D Array to three 2-D array
# 
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [239]:
#3-D Array
# this 1-axis means is gives user point of view one by one column
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [243]:
# hsplit() and hstack()
# hsplit is oppposite of hstack()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [269]:
''' Searching Arrays '''
''' > you can search an array for a ceratin value and return the indexes that get a match.
   > to sarch an array use the where() method '''
arr =np.array([1,2,3,4,5,6,7,8,8])
newarr=np.where(arr==8)
print(newarr)

x=np.where(arr%2==0)  # even
print(x)

x=np.where(arr%2==1)  # odd
print(x)



(array([7, 8], dtype=int64),)
(array([1, 3, 5, 7, 8], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


In [51]:
# search sorted , serchsorted() we are use 
# in this method output gives the index value
x=np.searchsorted(arr,7)
print(x)

xy= np.searchsorted(arr,8,side='right')  # in this line doon't gives actual output
print(xy)


6
8


In [57]:
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [75]:
''' Sorting Arrays '''
# sorting means putting elements in an ordered sequence
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print()

arr=np.array(['santhosh','kumar','resh','mani'])
print(np.sort(arr))
# 2-D
arr=np.array([['santhosh','kumar','resh','mani'],['santhosh','kumar','resh','mani']])
print(np.sort(arr))
print()
arr = np.array([[3, 2, 0, 1],[100,50,56,200]])
print(np.sort(arr))

[0 1 2 3]

['kumar' 'mani' 'resh' 'santhosh']
[['kumar' 'mani' 'resh' 'santhosh']
 ['kumar' 'mani' 'resh' 'santhosh']]

[[  0   1   2   3]
 [ 50  56 100 200]]


In [87]:
'''NumPy Array Filter '''
''' Getting some elements out of an existing array and creating a new array out of them is called filtering.
>In Numpy, you filter an array using a boolean index list.
>A boolean index list a list of booleans corresponding too indexes int he arra. '''

# If the value at an index is true that element is contained in the filtered array, if the value at that index is false that element is excluded from the filtered array.

arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=[True, False, True, False,True, False, True, False,True, False]
newarr=arr[x]
print(newarr)
print()
# creating the filer array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr=[]
for i in arr:
    if i>6:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)


[1 3 5 7 9]

[False, False, False, False, False, False, True, True, True, True]
[ 7  8  9 10]


In [3]:
# getting even numbers
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr=[]
for i in arr:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [13]:
# directly created  filter array
arr=np.array([1,2,3,4,5,6,7,8])
filter_arr=arr>4
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)
print()

arr=np.array([1,2,3,4,5,6,7,8])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False False False  True  True  True  True]
[5 6 7 8]

[False  True False  True False  True False  True]
[2 4 6 8]
