In [ ]:
'''NumPy ufuncs'''
# ufuncs stands for "universal function" and they are numpy functions that operate ndarray object.
# A universal function is a function that operates on ndarrays in an element
#element-by-element fashion ,supporting array broadcasting ,type casting, and several other standard features.

'''why use ufuncs?'''
# it is used to implemet vectorization in numpy which is way faster than itering over elements.
#Theey also provide broaadcasting methods likes reduce ,accumulate etc.
# arguments:
# where=boolean array or condition where the operations should take place.
# dtype=return type of elements.
# out=output array where the return value should be copied.

'''what is vectorization '''
# converting interating stmts into vector based operation is callled vectoriation.
# in this process without using for loop operations.
# It si faster as modern cpus are optimized foer such operations.


In [7]:
'''Zip()'''
a=[1,2,3,4,5]
b=[1,2,3,7,8]
c=[]
for i,j in zip(a,b):
    c.append(i+j)
print(c)



'''add()'''
import numpy as np
c=np.add(a,b)
print(c)
    

[2, 4, 6, 11, 13]
[ 2  4  6 11 13]


In [13]:
'''frompyfunc()'''
# it is alsonormal function in python.
#parameters:
#function = name of the function.
#inputs = no.of input arguments(arrays).
#outputs + no.of outputs arrays.

def myadd(a,b):
    return a+b
variable=np.frompyfunc(myadd,2,1)
print(variable([1,2,3],[4,5,6]))

[5 7 9]


In [33]:
print(type(np.add))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [37]:
if type(np.add)==np.ufunc:
    print("add is ufunc")
else:
    print("add is not ufunc")

add is ufunc


In [65]:
'''Arithmetic operations'''
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
newarr=np.add(arr1,arr2)
print(newarr)
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.remainder(arr1,arr2))  # mod() and remainder() both are same
print(np.divmod(arr1,arr2))    # returns the quotient and reamider
print(np.absolute(arr1))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[1 2 3 4 5]
(array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))
[1 2 3 4 5]


In [109]:
'''Rounding Decimals'''
# five ways
# truncation ,fix, rounding, floor, ceil.

arr=np.trunc([-123.456,6.4454])
print(arr)
print(np.fix(arr))  #trunc and fix both are same

rr1=np.around(34.32456,1)
print(rr1)

arr=np.floor([-123.456,6.4454]) # returns nearest value
print(arr)

arr=np.ceil([-123.456,6.4454]) # returns nearest value
print(arr)


[-123.    6.]
[-123.    6.]
34.3
[-124.    6.]
[-123.    7.]


In [161]:
'''numpy logs'''
# munpy provides functions to perform log at the base 2, e and 10.
arr=np.arange(1,10)
print(np.log2(arr))


arr=np.arange(1,10)
print(np.log(arr))

arr=np.arange(1,10)
print(np.log10(arr))

# log at any base log(value,base)
from math import log
nplog=np.frompyfunc(log,2,1)
print(nplog(10,2))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
3.3219280948873626


In [207]:
'''Summations'''
# what is the diff between summation and addition
# summation is the total value and add means addition of first and second elements.

arr1 = np.array([1, 2, 3])
arr2 = np.array([5,6,8])

newarr = np.add(arr1, arr2)

print(newarr)

#summation
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 8])

newarr = np.sum([arr1, arr2])

print(newarr)

# summation over an axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 8])

newarr = np.sum([arr1,arr2], axis=1)
print(newarr)

[ 6  8 11]
25
[ 6 19]


In [211]:
# cumulative sum
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.cumsum(arr))

[ 1  3  6 10 15 21 28 36 45 55]


In [237]:
'''numpy products'''
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.prod(arr))

# two arrays of product
arr1 = np.array([1, 2, 3])
arr2 = np.array([1,2,3])
newarr=np.prod([arr1,arr2])
print(newarr)

#product over on axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([1,2,3])
newarr=np.prod([arr1,arr2],axis=1)
print(newarr)

#cumulative product
arr1 = np.array([1, 2, 3])
arr2 = np.array([1,2,3])
newarr=np.cumprod([arr1,arr2])
print(newarr)

3628800
36
[6 6]
[ 1  2  6  6 12 36]


In [269]:
'''Difference'''
# discrete difference means substring two successive elements.
# diff()

arr=np.array([12,3,4,5,6,7,19])
print(np.diff(arr,n=2))

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)


[10  0  0  0 11]
[  5 -30]


In [3]:
'''LCM'''
# LCM=Lowest common factor multiple
# first of all two multiple numbers

import numpy as np
num1=10
num2=20
x=np.lcm(num1,num2)
print(x)

20


In [13]:
'''LCM in Arrays'''
# to find the lowest common multiple of all values in an array ,we can use reduce() method
arr=np.array([1,2,3,4,5])
x=np.lcm.reduce(arr)
print(x)

arr=np.arange(1,20)
x=np.lcm.reduce(arr)
print(x)

60
232792560


In [19]:
'''Numpy GCD'''
# Greatest common Denominator
# the GCD also knomn as HCF is hte biggest nnumber that is a facor of both of the numbers.

num1=10
num2=20
x=np.gcd(num1,num2)
print(x)

arr=np.array([23,45,67,21])
x=np.gcd.reduce(arr)
print(x)

10
1


In [47]:
'''Trigonometric Functions'''
#ufuncs sin(), cos(), tan() that takes values in radians the produces corresp values.

x=np.sin(np.pi/6)
print(x)

arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
x=np.sin(arr)
print(x)

0.49999999999999994
[1.         0.8660254  0.70710678 0.58778525]


In [51]:
'''convert degrees into Radians'''
# we can use ,deg2rad()
# radians=degrees*pi/180
arr=np.array([120,145,180,270])
x=np.deg2rad(arr)
print(x)

[2.0943951  2.53072742 3.14159265 4.71238898]


In [55]:
'''radians into degrees'''
#degree=radians*180/pi
arr=np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x=np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [79]:
''' Finding Angles'''
# inverse (arcsin,arccos,arctan).
#ufuncs provides arcsin(),arccos(),arctan().
# range os sin invesr is -1 to 1
x=np.arcsin(.4)
print(x)

0.41151684606748806


In [87]:
'''Angles of each value in Arrays'''
arr=np.array([1,-1,0.1])
x=np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [93]:
'''Hypotenues'''
# numpy provides the hypot() function that makes the base and perpendicular values and produces hypotenues based on pythgoras.
base=3
perp=16
x=np.hypot(base,perp)
print(x)

16.278820596099706


In [123]:
'''Hyperbolic functions'''
# ufuncs provides sinh(), cosh(), tanh() that value inn radians and produces corresponding sinh,coh,tanh.
x=np.sinh(np.pi/2)
print(x)

# arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
# x=np.cosh(arr)
# print(x)

'''inverse function values'''
arr=np.arcsinh(0.3)
print(arr)

arr=np.array([0.1,0.2,0.5])
x=np.arctanh(arr)
print(x)

2.3012989023072947
0.2956730475634224
[0.10033535 0.20273255 0.54930614]


In [149]:
'''NUmpy set operations'''
# set is a mathamatical is acollection of unique elemnts. 
# sets are used involving frequent intersection, uinon and difference operations.
arr=np.array([1,1,2,3,5,7,6,4,9,7,9,0,0,0,0])
print(np.unique(arr))

#union
arr=np.array([1,1,2,3,5,7,6,4,9,7,9,0,0,0,0])
arr1=np.array([1,1,2,7,9,0,11,12,17,0])
newarr=np.union1d(arr,arr1)
print(newarr)

#intercsetion
arr=np.array([1,1,2,3,5,7,6,4,9,7,9,0,0,0,0])
arr1=np.array([1,1,2,7,9,0,11,12,17,0])
newarr=np.intersect1d(arr,arr1,assume_unique=True)
print(newarr)

#Difference
arr=np.array([1,1,2,3,5,7,6,4,9,7,9,0,0,0,0])
arr1=np.array([1,1,2,7,9,0,11,12,17,0])
newarr=np.setdiff1d(arr,arr1,assume_unique=True)
print(newarr)

#symmetric Difference '''
arr=np.array([1,1,2,3,5,7,6,4,9,7,9,0,0,0,0])
arr1=np.array([1,1,2,7,9,0,11,12,17,0])
newarr=np.setxor1d(arr,arr1,assume_unique=True)
print(newarr)


[0 1 2 3 4 5 6 7 9]
[ 0  1  2  3  4  5  6  7  9 11 12 17]
[0 0 0 0 0 1 1 1 2 7 7 9 9]
[3 5 6 4]
[ 3  4  5  6 11 12 17]
